name: Laravel AWS CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate application key
      run: php artisan key:generate

    - name: Run Laravel tests
      run: php artisan test

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS Elastic Beanstalk
      run: |
        zip -r deploy.zip .
        aws elasticbeanstalk create-application-version --application-name LaravelApp --version-label ${{ github.sha }} --source-bundle S3Bucket="elasticbeanstalk-us-east-1-xxxxxxxxxxxx",S3Key="deploy.zip"
        aws elasticbeanstalk update-environment --environment-name LaravelApp-env --version-label ${{ github.sha }}

    - name: Run database migrations
      run: |
        aws elasticbeanstalk update-environment-property --environment-name LaravelApp-env --option-settings "Namespace=aws:elasticbeanstalk:application:environment,OptionName=RUN_MIGRATIONS,Value=true"

    - name: Clear Laravel cache
      run: |
        aws elasticbeanstalk update-environment-property --environment-name LaravelApp-env --option-settings "Namespace=aws:elasticbeanstalk:application:environment,OptionName=CLEAR_CACHE,Value=true"
